interface Equipo {
  nombre: string;
  torneos: string[];
  escudo: string;
}

export const Equipos: Equipo[] = [
  {
    nombre: '25 de Agosto',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Aguada',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Albatros',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Atenas',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Ateneo (maldonado)',
    torneos: ['U16 Femenino'],
    escudo: '',
  },
  {
    nombre: 'Auriblanco',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Bigua',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Bohemios',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Capitol',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Capurro',
    torneos: [
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Cordon',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U16 Femenino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Colon F.C.',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
      'U14 Femenino',
    ],
    escudo: '',
  },
  {
    nombre: 'Country El Pinar',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Defensor Sporting',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Defensores de Maroñas',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Deportivo Maldonado',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Deportivo de la Costa',
    torneos: [
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Goes',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Hebraica y Macabi',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Juventud',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Lagomar',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
  },
  {
    nombre: 'Larrañaga',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Larre Borges',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Layva',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Malvin',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Marne',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Miramar',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Montevideo BBC',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Nacional',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Nautico',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Olimpia',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Olivol Mundial',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Peñarol',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Plaza Helvetico',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Reducto',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'San Telmo - Rapido Sport',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Sayago',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Stockolmo',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Tabare',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Trouville',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Union Atletica',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Urunday Universitario',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Urupan',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Verdirrojo',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Welcome',
    torneos: [
      'U20 Masculino',
      'U18 Masculino',
      'U16 Masculino',
      'U14 Mixto',
    ],
    escudo: '',
    },
    {
    nombre: 'Yale',
    torneos: [
      'U20 Masculino',
      'U19 Femenino',
      'U18 Masculino',
      'U16 Femenino',
      'U16 Masculino',
      'U14 Femenino',
      'U14 Mixto',
    ],
    escudo: '',
    },
]